# Branch blocklist
branches:
  except:
    - class_clean

language: c
sudo: required

env:
    global:
        MPI_RUN_COMMAND=''

notifications:
  email:
    recipients:
      - manodeep@gmail.com
      - jseiler@swin.edu.au
    on_success: change
    on_failure: always

matrix:
  fast_finish: true

  include:
    - name: "OSX Clang"
      os: osx
      osx_image: xcode9.3
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-5 Trusty distrubution"
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=gcc-5 PYTHON_VERSION=3.7
      before_install:
        - gcc-5 --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-6 Xenial distrubution."
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=gcc-6 PYTHON_VERSION=3.7
      before_install:
        - gcc-6 --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-7 Xenial distrubution."
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: COMPILER=gcc-7 PYTHON_VERSION=3.7
      before_install:
        - gcc-7 --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-5 MPI Xenial distribution"
      os: linux
      dist: xenial 
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=mpicc PYTHON_VERSION=3.7 MPI_RUN_COMMAND='mpirun -np 5'
      before_install:
        - export CC=/usr/bin/gcc-5
        - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
        - export CC=mpicc
        - which mpicc
        - mpicc --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-6 MPI Xenial distribution"
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=mpicc PYTHON_VERSION=3.7 MPI_RUN_COMMAND='mpirun -np 5'
      before_install:
        - export CC=/usr/bin/gcc-6
        - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
        - export CC=mpicc
        - which mpicc
        - mpicc --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

    - name: "Linux gcc-7 MPI Xenial distribution"
      os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env: COMPILER=mpicc PYTHON_VERSION=3.7 MPI_RUN_COMMAND='mpirun -np 5'
      before_install:
        - export CC=/usr/bin/gcc-7
        - sudo apt-get install -y -q openmpi-bin libopenmpi-dev
        - export CC=mpicc
        - which mpicc
        - mpicc --version
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh

install:
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -q --yes -n test python=$PYTHON_VERSION nomkl
  - source activate test
  - conda install -q --yes -c anaconda gsl
  - conda install -q --yes -c conda-forge hdf5
  - pip install -r requirements.txt 

script:
  - make -r CC=$COMPILER tests
